version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: orb-slam-3:dev
    container_name: orb-slam-3-dev
    user: "1000:1000"
    volumes:
      - .:/home/user/ORB_SLAM3
      # - /mnt/wslg:/mnt/wslg
      # - /tmp/.X11-unix:/tmp/.X11-unix
    # environment:
    #   - DISPLAY=:0
    #   - WAYLAND_DISPLAY=$WAYLAND_DISPLAY 
    #   - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    #   - PULSE_SERVER=$PULSE_SERVER
    ports:
      - 8888:8888
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    tty: true